"""added followed to Profile

Revision ID: 1583fec7421b
Revises: d7b26c1ada7b
Create Date: 2023-06-09 04:54:34.887699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1583fec7421b'
down_revision = 'd7b26c1ada7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['profile.id'], )
    )
    op.drop_table('Profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profile',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['profile.id'], name='Profile_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['profile.id'], name='Profile_follower_id_fkey')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
